feat: Add replacementUuid support in BundleRequest
onbjerg/ethers-flashbots pull request #63
Opened 2023-10-31 09:54 UTC by TwelfthGhast

Add support for sending bundles with uuids for future replacement/cancellations. Will probably at some point also figure out how to get eth_cancelBundle into this crate.

https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint

2023-11-12 22:52 UTC, onbjerg requested changes
Can we use a UUID type?

2023-11-12 22:52 UTC, onbjerg commented on src/bundle.rs
> +        self.uuid = Some(uuid.clone());
I don't think the clone is necessary since we take ownership

2023-11-17 10:16 UTC, TwelfthGhast commented
Switched to Uuids and rebased.

2024-01-24 01:17 UTC, onbjerg approved these changes

2024-01-24 01:17 UTC, onbjerg commented
thanks!

2024-01-24 01:17 UTC, merged